before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: HVCGYr+I+dFWPeVJSQh6jjGh0i/fq8ARofUrLAhWKJYpq/k/1CBSWPF3GoNVpH6qOelKjfhG8seHh/PN8Cpyz6g/25efsiS51zF6uGsUq6lzsQ6f3wxqG02Usjt1ZYbmRpoRl4HL2918k9AkGUcFxE1C4IwdjZRopoWpp8PEdJTKr2Pl/Q17Rb0ihSlqdSOojr7duGiuIMR1d5Nqj/Ibw87r/jmt2jxkPg5XNi7id3f/bSWoUZCQPwCw7BqyMIs9jGuEmsbL1nxAUq6w/jQoB2E6MaFFEqkYQj1Lfq0m3l+5fbi/HgMC6BCwZw+gduYCwuZkfdkXo4MUt2J8uy0bMaQh54foJ/U1CGd1gNZAxX4JQ43FbVltJAyriCfhdEDPt2XboJH7xOMGvABWHKVQBs+mwgrgCCJhPw28GhS+zPe7Wa4DPe6icZMZL/i7uMu95tBxCwVka4OvQG0AYjymB9AE43Pi1u4493ax/gESs8pHXmibeSxh7WPvM7saR/GaLLY8wrD9AxvA1/VqfOc1w8+/AXdJ68yqYza4K8ZE3/2NSgGI7hIZrHifXLtVHuqEUw4qTmJxYwFsaZhPNtLD2PTnDW4K7Ix82WrO5/NS50IOPOXHRh3XlQHaIsxz9VDuXB1TRO38gOFPthf0fV2PL6DVBvO3MAVDqZ4y83ebdXU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
